language: android
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - lynx
env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-22
    - android-26
    - sys-img-armeabi-v7a-android-22

  licenses:
    - android-sdk-license-.+

before_script:
  - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew clean build connectedCheck

after_failure:
  - |
      if [ -f "$TRAVIS_BUILD_DIR/android-rgba/build/reports/lint-results.html" ]; then
        lynx -dump "$TRAVIS_BUILD_DIR/android-rgba/build/reports/lint-results.html"
      fi

notifications:
  slack:
    - secure: "cfUrS6sy4ttWQPDtWk0nR1vllgkaCnhb808W7Su72XQAJXtSugihLT2zc2oI4MDOCBKYDMEwacPyT7555Jskvgu6ZBmPoH/SejknLXvnwnQ0Cfe8pL66xl0J40KjlnkW8NxF1r54yyuXdB6BZ7zTVyjuTFjlhR9xuCzQHSI2bSUXWHOrNnwrLPBjPz8k5O8lgRU9YoTPx24O0z0RrmbCkX+qrZnwTOg3NtpLoDxVDD2qv9LZ2MH19cUgLNuL/vwurIegQeNk5JnO2X7n306ke+MvyaYCrRceivTwOgR7hKIEw0TUt/JBJ5SdupAXR7iAJGdPht1DgB6NgOu/osjwBXKxLjeAv8r7qWH75yf+n3A1IpWiEKRsgjxkJujEkGDW+D2PMcQwiFb7HhKVfpoqp58gVOQKL/XfW0gKrzL3mjx5LNcLvIq5XA/Ysc4yg8a/skPMJ7QMmoX1r9lz8/fNafOy4KBk5J6XkrgzJTQ2Gyc31dQkPXUe/e0gi/OX+MgGNI2QRdtj0CwgXgqupWhIvBRb2mnpAlCjh0rxjfTtc/PX1d3rTIzBwMci5y/fONlodLPpo2TqDStA+kf+AM3vyUlqf++egjie0tcRaaa+Uji0Spz3whMJLZ+vTsUyacDdvtGmGPRnBCN9Z6ikxymePW+D3WipjAEQXmuIqtT9FjA="
    - secure: "arsW7ysSVRwJ8GpyaCudyzTQqrrXuXrEwlPAQrhwNZnBWonM4iniRQz9RE0wDzrF8u2mi1ML9rKmjN+GXnA04Pk3o7CUv/WO7IF68kqa6Jt1BYBFTXV0q2VrGAgCdGxc8F7pUfZKgDqtygUzfifN8aKSte0twUAVo8ifCalV8be+EeL9AdMRxz3d76FqqRlKBNveL8L/hfURme+MXT2TvRPsSWe81XLK/Iqb7cLI42f39A4e777c2x6dYPQTaksplRemJl9gEQqyafXKL5CfErr8n/WCTO8U0OPH/n2W4YNxH70a53xvvSPwTcakAZ5qwX+TENkrxpBXlHVDn8fetZnJOsgJhSexYGjd9IhvH+zmD3jCP4YT7HQNA6I2FnoDoMjxHlXj6i328vPo3jsU/Ey0/1toSXJpQgJVsR80P9Dfj8SBtRveZUmyREY3sr/p8LcFMu+n6DMvdb2UNwKtq0lIMGHRpA5qZXWnBm68ZlFbQ5Ynt5PMsv1w2/KYfYX3kQFLQuZ73L5Nz1G8l9yXSooGWakHym4+kxUVuGB7BSAJAC/MRXYu6lqF3sTgswcHMoD/0FVt73TUkKD5JukrwgWSUzhPPu9wygXL4JnhlSePSbGNqADI9hjDWh4LAZxltbPS8npqC5uuBtOCID7XUP+Qh2LYmWTXJGmUAsN4fJU="
